### ISSUE TITLE
Дружище

### ISSUE THREAD

**Issue by Overlord14** [ilnarildarovuch/Fusion-Mod-Translate-to-Russian#1]
Делаешь большое дело, надеюсь доведешь до конца. Это для андроида или для ПК ? И когда, думаешь, будет готово ?

**Comment by ilnarildarovuch** [comment]
Это будет multi. Точно сказать, сможем ли мы закончить скоро или закончить вообще не могу знать. (Есть другая команда, которая уже сделала первый билд). А ещё у нас частая проблема с декомпиляцией, но вчера все ошибки стали исправляемые. Когда исправлю, закину на репу.
