### ISSUE TITLE
Исходники

### ISSUE THREAD

**Issue by Climeron** [ilnarildarovuch/Fusion-Mod-Translate-to-Russian#2]
Сейчас уже вышла новая версия 2.1.4, и чтобы было проще делать моды не помешали бы исходники. Я много что перепробовал, чтобы декомпильнуть игру, но получаю либо пустые методы, либо методы заполненные указателями, либо частично восстановленные методы. Хотелось бы узнать, как ты достал исходники.

**Comment by ilnarildarovuch** [comment]
Эххх. Тут другая проблема, лол, они не работают. Ведь игра скомпилирована Il2Cpp, сейчас я работаю через сабмод на MelonLoader: https://github.com/ArifRios1st/PVZ-Hyper-Fusion-Mod. Правда его еще и патчить приходится. А так, если игра была-бы скопилирована на Mono, может и сработало-бы. (Приложение для декомпиляции: AssetRipper). Как раз думал выпустиь force push на GitHub

**Comment by ilnarildarovuch** [comment]
Так-что тут ситуация не лучше

**Comment by Climeron** [comment]
С Mono ситуация гораздо лучше. Il2Cpp свои палки в колёса вставляет)

**Comment by ilnarildarovuch** [comment]
Тут полностью согласен(

**Comment by ilnarildarovuch** [comment]
Кстатич ты знаешь, как сменить шрифт в MelonLoader, там вместе все реддитом голову сломали, может ты чего скажешь, пожалуйста: https://github.com/ArifRios1st/PVZ-Hyper-Fusion-Mod

**Comment by Climeron** [comment]
Со шрифтами пока не игрался и пока не знаю, буду ли я с ними что-то делать.

**Comment by ilnarildarovuch** [comment]
Хорошо (кстати, отличный чат)

**Comment by Climeron** [comment]
Слушай, а у тебя есть доступ к дискорду?

**Comment by ilnarildarovuch** [comment]
Так, само по себе нет, но я чаще использую Тор, как прокси

**Comment by Climeron** [comment]
Просто можем списаться где-нибудь. Мне удобней в дс. Но если возможности нет, можно и в телеге.

**Comment by ilnarildarovuch** [comment]
Можно, почему нет? Но пока не могу

**Comment by ilnarildarovuch** [comment]
DS: ilnarildarovuch
